### PR TITLE
A branch has been created named Mar b01

### PR DESCRIPTION
**Pull request by marwansubhi**
A new class have been created under a new branch to be discussed with the group

### CODE REVIEW

**Comment by marwansubhi** [comment]
Good morning guys

**Comment by anitastati** [comment]
good morning

**Comment by KatrinSi** [comment]
Hello!

**Comment by ayderham** [comment]
im here

**Comment by Alex-Cret** [comment]
we are here

**Comment by marwansubhi** [comment]
What do you think about the new update
Could you please review it and give me your feedback?

**Comment by KatrinSi** [comment]
It definitely should be merged :)

**Comment by EllaKoch** [comment]
it looks great!

**Comment by marwansubhi** [comment]
Thank you Kate, i will wait for others to review and get their feedback

**Comment by anitastati** [comment]
great job !

**Comment by Alex-Cret** [comment]
yes

**Comment by Alex-Cret** [comment]
yes

**Comment by EllaKoch** [comment]
checked it out on my local. Nice job, Marwan

**Pull request merged**
