### PR TITLE
My first b

### PR DESCRIPTION
**Pull request by vidash50**
I see all

### CODE REVIEW

**Comment by vidash50** [comment]
I'm here

**Comment by vidash50** [comment]
Thank you all for your collaboration.

**Comment by ayderham** [comment]
im here

**Comment by marwansubhi** [comment]
Did you guys have a final word yet?

**Comment by ayderham** [comment]
here

**Comment by marwansubhi** [comment]
please send more comments

**Comment by Alex-Cret** [comment]
from InteliJ

**Comment by ayderham** [comment]
is this going to send me on my email, all new comments?

**Comment by vidash50** [comment]
Yes I see it. You doing good

**Comment by vidash50** [comment]
Do you see mine?

**Pull request merged**
